server:
  name: go-postgresql-tutorial
  port: 8080

sql:
  driver: postgres
  data_source_name: postgres://postgres:abcd1234@localhost:5432/masterdata?sslmode=disable

log:
  level: info
  duration: duration
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: body
  response: response
  size: size
