server:
  name: go-gin-sql-tutorial
  port: 8080

sql:
  driver: postgres
  data_source_name: postgres://xkjofgbu:MKmT3B0PPIZ6pr057wEHFUMvtad5nXex@satao.db.elephantsql.com/xkjofgbu

log:
  level: info
  fields: appId,service,mobileNo,creditCard,corrId
  duration: duration
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: request
  response: response
  duration: duration
  size: size
  masks: mobileNo,creditCard
  constants:
    app_id: "123"
    service: payment
  map:
    mobile_no: header.mobileNo
    credit_card: header.creditCard
    corr_id: header.corrId
    email: body.email
    username: body.username
