server:
  name: go-postgresql-tutorial
  port: 8080

sql:
  driver: postgres
  data_source_name: postgres://postgres:abcd1234@localhost:5432/masterdata?sslmode=disable

log:
  level: info
  fields: appId,service,mobileNo,creditCard,corrId
  duration: duration
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: request
  response: response
  duration: duration
  size: size
  masks: mobileNo,creditCard
  constants:
    app_id: "789"
    service: promtpay
  map:
    mobile_no: header.mobileNo
    credit_card: header.creditCard
    corr_id: header.corrId
    email: body.email
    username: body.username
